language: node_js
node_js:
  - "node"
  - "lts/*"
  - "6"
cache: yarn
"os":
  - "linux"
# Node js is not supported on macOS on Travis
# Windows is not supported at all. Bummer.
script:
  - export NODE_ENV="ci"
  - echo 'node:' `node --version`
  - echo 'npm:' `npm --version`
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
   # latest yarn; at this commit, using 1.0.1
   # add `-- --version 1.0.1` to fix a version (see https://yarnpkg.com/en/docs/install#alternatives-tab)
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo 'yarn:' `yarn --version`
  - yarn
  - echo 'branch:' `git rev-parse --abbrev-ref HEAD`
  - echo 'tags:' `git name-rev --tags --name-only $(git rev-parse HEAD)`
  - echo 'sha:' `git rev-parse --verify HEAD`
  - echo $NODE_ENV
  - yarn test
  - yarn run legally -- -l -r
