branches:
  except:
    - /^travis\/.*/
language: node_js
cache:
  directories:
    - "node_modules"
"os":
  - linux
# Node js is not supported on macOS on Travis
# Windows is not supported at all. Bummer.
jobs:
  include:
    - node_js: '10' # npm test
