branches:
  except:
    - /^travis\/.*/
language: node_js
cache:
  directories:
    - "node_modules"
"os":
  - linux
# Node js is not supported on macOS on Travis
# Windows is not supported at all. Bummer.
jobs:
  include:
    # stage test
    - node_js: '6' # npm test
    - node_js: '8' # npm test
      script:
        - npm test
        - npm run reportCoverage
  # stage tag
    - stage: tag
      node_js: '8'
      install: skip
      script:
        - npm run legalReport
        - scripts/travisGithubTag.sh
