
# MUDOs
# - Build Teardown mentions the gathering of test reports etc. Is that a new feature?
#   Yes. See https://confluence.atlassian.com/bitbucket/test-reporting-in-pipelines-939708543.html

# NOTE: Not testing on node12 / node latest for now, because there is no binary download for nodegit, and building it
#       it from src fails. It also builds from src for node10, but that succeeds.

image: node:10

definitions:
  steps:
    - step: &testNpmGE5
        name: Latest Node N
        image: IMAGE
        caches:
          - npm
        script:
          - git submodule update --init
          - scripts/common/npm/testCi.sh
  caches:
    node6: node_modules
    # for node with npm >=5, cache the npm cache at ~/.npm (per node version),
    # not node_modules, which is replaced by npm ci
    node8: ~/.npm
    node10: ~/.npm
    node12: ~/.npm
  branches:
    - branch: &fullTestAndTag
        - parallel:
            - step:
                name: Latest Node 6
                image: node:6
                caches:
                  - node6
                script:
                  - git submodule update --init
                  - scripts/common/npm/testNpm3.sh
            - step:
                <<: *testNpmGE5
                name: Latest Node 8
                image: node:8
                caches:
                  - node8
            - step:
                <<: *testNpmGE5
                name: Latest Node 10
                image: node:10
                caches:
                  - node10
        - step:
            name: Tag
            image: node:10
            caches:
              - node10
            script:
              - git submodule update --init
              - scripts/common/git/tagBitbucket.sh

pipelines:
  branches:
    master: *fullTestAndTag
    feature/**: *fullTestAndTag
