image: node:10

pipelines:
  branches:
    feature/*:
      - parallel:
        - step:
            name: Latest Node 6
            image: node:6
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
        - step:
            name: Latest Node 8
            image: node:8
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
        - step:
            name: Latest Node 10
            image: node:10
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh

# MUDOs
#
# - nodegit build fails
# - cache is shared between versions of node, and that is not the intention
# - script does not fail if early commands fail
#
# - Build Teardown mentions the gathering of test reports etc. Is that a new feature?
#
# - node6 works because of cache of node 8/10, but doesn't work on its own, because we are using npm 5 commands and npx,
#   which don't exist in npm 3 for node 6
