image: node:10

pipelines:
  branches:
    feature/*:
      - parallel:
        - step:
            name: Latest Node 6
            image: node:6
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
        - step:
            name: Latest Node 8
            image: node:8
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
        - step:
            name: Latest Node 10
            image: node:10
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
