image: node:10

pipelines:
  branches:
    feature/*:
      - parallel:
        - step:
            name: Latest Node 6
            image: node:6
            caches:
              - node
            script:
              - git submodule update --init
              - scripts/common/npm/testNpm3.sh
        - step:
            name: Latest Node 8
            image: node:8
            caches:
              - node8
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
        - step:
            name: Latest Node 10
            image: node:10
            caches:
              - node10
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
        - step:
            name: Latest Node
            image: node
            caches:
              - nodeLatest
            script:
              - git submodule update --init
              - scripts/common/npm/testCi.sh
definitions:
  caches:
    # for node with npm >=5, cache the npm cache at ~/.npm (per node version),
    # not node_modules, which is replaced by npm ci
    node8: ~/.npm
    node10: ~/.npm
    nodeLatest: ~/.npm

# MUDOs
#
# - nodegit build fails
# - postinstall `npm run update_credits` fails
#
# - Build Teardown mentions the gathering of test reports etc. Is that a new feature?
#   Yes. See https://confluence.atlassian.com/bitbucket/test-reporting-in-pipelines-939708543.html
